#!/usr/bin/env bash
git branch -D gh-pages
git checkout --orphan gh-pages
git rm -rf ./app
git rm -rf ./utils
git rm -rf ./build
git rm -rf ./gulp
#git clean -fd -e dist
git clean -fd
mv build/* ./
# rm -fr ./node_modules
#shopt -s dotglob
git add -A .
git commit -am 'build gh-pages'
git push -u -f origin gh-pages:gh-pages
